package com.lu.entity;

import org.springframework.stereotype.Component;

/**
 * card
 * 
 * @author bianj
 * @version 1.0.0 2020-09-28
 */

public class Card implements java.io.Serializable {
    /** 版本号 */
    private static final long serialVersionUID = -8753549211665562567L;

    /* This code was generated by TableGo tools, mark 1 begin. */

    /** cid */
      String cid = "ssdd";

    /** city */
    private String city;

    /* This code was generated by TableGo tools, mark 1 end. */

    /* This code was generated by TableGo tools, mark 2 begin. */

    /**
     * 获取cid
     * 
     * @return cid
     */
    public String getCid() {
        return this.cid;
    }

    /**
     * 设置cid
     * 
     * @param cid
     */
    public void setCid(String cid) {
        this.cid = cid;
    }

    /**
     * 获取city
     * 
     * @return city
     */
    public String getCity() {
        return this.city;
    }

    /**
     * 设置city
     * 
     * @param city
     */
    public void setCity(String city) {
        this.city = city;
    }

    /* This code was generated by TableGo tools, mark 2 end. */
}