package com.lu.entity;

/**
 * people
 * 
 * @author bianj
 * @version 1.0.0 2020-09-28
 */
public class People implements java.io.Serializable {
    /** 版本号 */
    private static final long serialVersionUID = 3085962225972525722L;

    /* This code was generated by TableGo tools, mark 1 begin. */

    /** pid */
    private String pid;

    /** name */
    private String name;

    /** school */
    private String school;

    /* This code was generated by TableGo tools, mark 1 end. */

    /* This code was generated by TableGo tools, mark 2 begin. */

    /**
     * 获取pid
     * 
     * @return pid
     */
    public String getPid() {
        return this.pid;
    }

    /**
     * 设置pid
     * 
     * @param pid
     */
    public void setPid(String pid) {
        this.pid = pid;
    }

    /**
     * 获取name
     * 
     * @return name
     */
    public String getName() {
        return this.name;
    }

    /**
     * 设置name
     * 
     * @param name
     */
    public void setName(String name) {
        this.name = name;
    }

    /**
     * 获取school
     * 
     * @return school
     */
    public String getSchool() {
        return this.school;
    }

    /**
     * 设置school
     * 
     * @param school
     */
    public void setSchool(String school) {
        this.school = school;
    }

    /* This code was generated by TableGo tools, mark 2 end. */
}